#!/bin/sh
# original code github.com/cu-ecen-5013/ldd3/blob/master/

config_pins()
{
	cd /sys/class/gpio
	echo 50 > export
	cd gpio50
	echo out > direction
	
	config-pin P9_24 uart
	config-pin P9_26 uart
}

fingerprint_load()
{
	module=fingerprintModule
	device=fingerprintModule
	mode="666"

	cd `dirname $0`
	set -e
	# Group: since distributions do it differently, look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
	    group="staff"
	else
	    group="wheel"
	fi

	insmod ./$module.ko || exit 1
	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	rm -f /dev/${device}
	mknod /dev/${device} c $major 0
	chgrp $group /dev/${device}
	chmod $mode  /dev/${device}
}

fingerprint_unload()
{
	module=fingerprintModule
	device=fingerprintModule
	cd `dirname $0`

	# invoke rmmod with all arguments we got
	rmmod $module || exit 1

	# Remove stale nodes
	rm -f /dev/${device}
}

case "$1" in
	start)
		echo "Fingerprint sensor connected"
		fingerprint_load
		;;
	stop)
		echo "Fingerprint sensor disconnected"
		fingerprint_unload
		;;
esac

exit 0
