#!/bin/sh
# original code github.com/cu-ecen-5013/ldd3/blob/master/

nrf_load()
{
	module=nrf
	device=nrf
	mode="666"

	cd `dirname $0`
	set -e
	# Group: since distributions do it differently, look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	insmod ./$module.ko || exit 1
	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	rm -f /dev/${device}
	mknod /dev/${device} c $major 0
	chgrp $group /dev/${device}
	chmod $mode  /dev/${device}
}

nrf_unload()
{
	module=nrfModule
	device=nrfModule
	cd `dirname $0`

	# invoke rmmod with all arguments we got
	rmmod $module || exit 1

	# Remove stale nodes
	rm -f /dev/${device}
}

case "$1" in
	start)
		echo "nrf connected"
		nrf_load
		;;
	stop)
		echo "nrf disconnected"
		nrf_unload
		;;
esac

exit 0
